Re former setup
sanadwj/re-former pull request #1
Opened 2020-09-18 21:34 UTC by sanadwj

## what this PR for:
- Generate the rais app
- Create user model and validations
- Create a user controller and it's methods 
- Add the HTML forms, form_tag, form_for
- Add edit method

2020-09-18 22:19 UTC, mosesogwo requested changes
**Hello :wave: Nice work on this :+1:**
Please see my comments on your code below and effect the required changes.

Here are some other **optional improvements** you could make
-  create a partial for user form and reuse in edit and new view
- on your form, you could display a list of the error messages if they exist (with  #errors and full_messages usage) 
- validate the email format by using either a regular expression or a built in URI method.

_**Kindly make these changes and submit another code review request.**_

**Any questions? You can reach me on Slack (Moses Ogwo)**

**Cheers:stars:**

### Status: Changes Requested:exclamation:

2020-09-18 22:19 UTC, mosesogwo commented on app/views/users/new.html.erb
> +<form accept-charset="UTF-8" action="/users" method="post" >
Use the rails _users\_path_ helper for the action option here.

2020-09-18 22:19 UTC, mosesogwo commented on app/views/users/new.html.erb
> +  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token
Where is the closing ERB tag for authenticity token here?

2020-09-18 22:19 UTC, mosesogwo commented on app/views/users/new.html.erb
> +  <%= f.text_field :email, placeholder:"Email" %>
Use **f.email_field** instead of f.text_field here

2020-09-18 22:52 UTC, sanadwj commented
@mosesogwo, Thanks for the review.
We edit all the changes

2020-09-18 23:47 UTC, elmejdki requested changes
# status: require changes :recycle: 
## Well done, guys :+1: :100: :clap: you are almost there just some couple changes :hammer: :wrench: and your project will be approved :checkered_flag: .

I have left some comments below please check them.

## Happy Coding :tophat:

2020-09-18 23:47 UTC, elmejdki commented on app/views/users/_form.html.erb
> +<form accept-charset="UTF-8" action="users_path" method="post" >
- user_path method goes without quotes into action.

2020-09-18 23:47 UTC, elmejdki commented on app/views/users/_form.html.erb
> +  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token >
you are messing the ERB closing tag in from_authenticity_token as mentioned by the previous TSE.

2020-09-18 23:47 UTC, elmejdki commented on app/views/users/_form.html.erb
> +<%= form_tag("/users", method: "post") do %>
use also users_path in the form_tag as in here: 
` form_tag(users_path) do`

2020-09-21 16:57 UTC, BrittanyBlake approved these changes
### Status: Approved ✅ 
****
### Hi Team! 👋 
### Great job implementing the requested changes!! 🎖️ It's a 👍 from me! Go ahead and merge this pull request and keep up the good work 😄
****

 Good Luck and Happy Coding! 🍀 👩🏾‍💻

2020-09-21 17:35 UTC, merged